- name: db-change
  color: "d93f0b"
  description: "PR changes Supabase migrations or edge functions."

- name: risk-high
  color: "b60205"
  description: "PR touches high-risk auth/RLS/policy/permission surfaces."
